#Workflow name
name: pull-request
on:
  #Manually trigger workflow runs
  workflow_dispatch:
  #Trigger the workflow on push from the main branch
  push: 
    branches:
     - A04
  pull_request:
    branches:
     - main
jobs:
  #Test's job
  tests:
   runs-on: ubuntu-latest
   name: Running tests
   steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 17 
       uses: actions/setup-java@v1
       with:
          java-version: 17
          
     - name: Run unit tests
       run: mvn test
       
     - name: Building jar
       run: |
          mvn -B package --file pom.xml
          mvn clean install
          mkdir pcee && cp target/demo-0.0.1-SNAPSHOT.jar pcee
          cp pcee/*.jar ami
          cd ami && ls --all

     - name: Packer build
       uses: ExitoLab/packer_build_action_aws@v0.2.10
       with:
         templateFile: 'ami.json'
         workingDir: 'ami'
       env:
           AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: us-east-1
